/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Geraldine Acevedo Restrepo
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        register_name_txt = new javax.swing.JTextField();
        register_cedula_txt = new javax.swing.JTextField();
        register_tel_txt = new javax.swing.JTextField();
        register_direc_txt = new javax.swing.JTextField();
        register_email_txt = new javax.swing.JTextField();
        register_city_txt = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        user_save_btn = new javax.swing.JButton();
        user_mostrar_btn = new javax.swing.JButton();
        user_editar_btn = new javax.swing.JButton();
        user_delete_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registro de usuarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Cédula:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Teléfono:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Direción:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Ciudad:");

        register_cedula_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_cedula_txtActionPerformed(evt);
            }
        });

        jToolBar2.setBackground(new java.awt.Color(0, 102, 255));
        jToolBar2.setRollover(true);
        jToolBar2.setPreferredSize(new java.awt.Dimension(100, 30));

        user_save_btn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        user_save_btn.setText("Guardar");
        user_save_btn.setFocusable(false);
        user_save_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_save_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        user_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_save_btnActionPerformed(evt);
            }
        });
        jToolBar2.add(user_save_btn);

        user_mostrar_btn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        user_mostrar_btn.setText("Mostrar");
        user_mostrar_btn.setFocusable(false);
        user_mostrar_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_mostrar_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        user_mostrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_mostrar_btnActionPerformed(evt);
            }
        });
        jToolBar2.add(user_mostrar_btn);

        user_editar_btn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        user_editar_btn.setText("Editar");
        user_editar_btn.setFocusable(false);
        user_editar_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_editar_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(user_editar_btn);

        user_delete_btn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        user_delete_btn.setText("Eliminar");
        user_delete_btn.setFocusable(false);
        user_delete_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_delete_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(user_delete_btn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(register_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(register_tel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register_email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(register_cedula_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(register_direc_txt)
                    .addComponent(register_city_txt))
                .addContainerGap(7, Short.MAX_VALUE))
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(register_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(register_cedula_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(register_tel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(register_direc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(register_email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(register_city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_save_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_save_btnActionPerformed

    private void register_cedula_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_cedula_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_cedula_txtActionPerformed

    private void user_mostrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_mostrar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_mostrar_btnActionPerformed

    public JButton getUser_delete_btn() {
        return user_delete_btn;
    }

    public JButton getUser_editar_btn() {
        return user_editar_btn;
    }

    public void setUser_editar_btn(JButton user_editar_btn) {
        this.user_editar_btn = user_editar_btn;
    }

    public JButton getUser_mostrar_btn() {
        return user_mostrar_btn;
    }

    public void setUser_mostrar_btn(JButton user_mostrar_btn) {
        this.user_mostrar_btn = user_mostrar_btn;
    }

    public JTextField getRegister_cedula_txt() {
        return register_cedula_txt;
    }

    public void setRegister_cedula_txt(JTextField register_cedula_txt) {
        this.register_cedula_txt = register_cedula_txt;
    }

    public JTextField getRegister_city_txt() {
        return register_city_txt;
    }

    public void setRegister_city_txt(JTextField register_city_txt) {
        this.register_city_txt = register_city_txt;
    }

    public JTextField getRegister_direc_txt() {
        return register_direc_txt;
    }

    public void setRegister_direc_txt(JTextField register_direc_txt) {
        this.register_direc_txt = register_direc_txt;
    }

    public JTextField getRegister_email_txt() {
        return register_email_txt;
    }

    public void setRegister_email_txt(JTextField register_email_txt) {
        this.register_email_txt = register_email_txt;
    }

    public JTextField getRegister_name_txt() {
        return register_name_txt;
    }

    public void setRegister_name_txt(JTextField register_name_txt) {
        this.register_name_txt = register_name_txt;
    }

    public JTextField getRegister_tel_txt() {
        return register_tel_txt;
    }

    public void setRegister_tel_txt(JTextField register_tel_txt) {
        this.register_tel_txt = register_tel_txt;
    }

    public JTextField getRegister_cedula_btn() {
        return register_cedula_txt;
    }

    public void setRegister_cedula_btn(JTextField register_cedula_btn) {
        this.register_cedula_txt = register_cedula_btn;
    }

    public JTextField getRegister_city_btn() {
        return register_city_txt;
    }

    public void setRegister_city_btn(JTextField register_city_btn) {
        this.register_city_txt = register_city_btn;
    }

    public JTextField getRegister_direc_btn() {
        return register_direc_txt;
    }

    public void setRegister_direc_btn(JTextField register_direc_btn) {
        this.register_direc_txt = register_direc_btn;
    }

    public JTextField getRegister_email_btn() {
        return register_email_txt;
    }

    public void setRegister_email_btn(JTextField register_email_btn) {
        this.register_email_txt = register_email_btn;
    }

    public JTextField getRegister_name_btn() {
        return register_name_txt;
    }

    public void setRegister_name_btn(JTextField register_name_btn) {
        this.register_name_txt = register_name_btn;
    }

    public JTextField getRegister_tel_btn() {
        return register_tel_txt;
    }

    public void setRegister_tel_btn(JTextField register_tel_btn) {
        this.register_tel_txt = register_tel_btn;
    }

    public void setUser_delete_btn(JButton user_delete_btn) {
        this.user_delete_btn = user_delete_btn;
    }

    public JButton getUser_save_btn() {
        return user_save_btn;
    }

    public void setUser_save_btn(JButton user_save_btn) {
        this.user_save_btn = user_save_btn;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField register_cedula_txt;
    private javax.swing.JTextField register_city_txt;
    private javax.swing.JTextField register_direc_txt;
    private javax.swing.JTextField register_email_txt;
    private javax.swing.JTextField register_name_txt;
    private javax.swing.JTextField register_tel_txt;
    private javax.swing.JButton user_delete_btn;
    private javax.swing.JButton user_editar_btn;
    private javax.swing.JButton user_mostrar_btn;
    private javax.swing.JButton user_save_btn;
    // End of variables declaration//GEN-END:variables
}
